#!/bin/bash

# Tag for the image variant we are using
TAG=ojdk7-deb

docker run -i -t --rm --name shibboleth-build --hostname ${TAG} \
    --volume=${PWD}/user:/home/user \
    $@ \
    shibboleth-build-docker:${TAG}
