#
# Corretto 8 and 11 image build workflow.
#
# Every time something is pushed to the "main" branch,
# build multi-architecture container images based on
# Amazon Corretto 8 and 11. Push these images to Docker Hub.
#
name: Build Corretto Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-corretto-images:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4.1.4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Corretto 8 multi-architecture image
      run: |
        docker buildx build --platform=linux/amd64,linux/arm64 \
          --no-cache --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/shibboleth-build-docker:amazon8 \
          amazoncorretto-8

    - name: Build and push Corretto 11 multi-architecture image
      run: |
        docker buildx build --platform=linux/amd64,linux/arm64 \
          --no-cache --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/shibboleth-build-docker:amazon11 \
          amazoncorretto-11
